### ISSUE TITLE
[BUG] app keeps stopping 

### ISSUE THREAD

**Issue by rajarshikhatua100** [JonasBernard/FakeStandby#53]
**Describe the bug**

**To Reproduce**
1. download from f - droid
2. open the app
3. toggle on
4. turn on accessibility
5. the app crashes 

**Screenshots**
![Screenshot_20230124_145923_AppErrorsTracking](https://user-images.githubusercontent.com/77912617/214256284-e4a35880-3870-4ee8-b101-02b1f168f176.jpg)

**Device information:**
 - Device: Samsung galaxy s20FE
 - Android Version: 13
 - App Version : 1.3.0

error log - 
Generated by AppErrorsTracking
Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: samsung
[Device Model]: SM-G780F
[Display]: TP1A.220624.014.G780FXXUAEVK3
[Android Version]: 13
[API Version]: 33
[System Locale]: en_IN
[Package Name]: android.jonas.fakestandby
[Error Type]: Jvm
[Crash Time]: 2023-01-24T14:57:34.695
[Stack Trace]:
java.lang.IllegalArgumentException: android.jonas.fakestandby: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:767)
	at android.app.PendingIntent.getService(PendingIntent.java:729)
	at a.a.<init>(Unknown Source:21)
	at android.jonas.fakestandby.service.AccessibilityOverlayService.onServiceConnected(SourceFile:2)
	at android.accessibilityservice.AccessibilityService.dispatchServiceConnected(AccessibilityService.java:826)
	at android.accessibilityservice.AccessibilityService.-$$Nest$mdispatchServiceConnected(Unknown Source:0)
	at android.accessibilityservice.AccessibilityService$2.onServiceConnected(AccessibilityService.java:2645)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:3016)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by PeterKW** [comment]
https://github.com/JonasBernard/FakeStandby/issues/55

**Comment by KelvinCrag** [comment]
Use version [1.33](https://f-droid.org/repo/android.jonas.fakestandby_10.apk)  and hide update.

**Comment by JonasBernard** [comment]
This should be fixed in version 1.3.5. is it?
